name: suninyourgarden
favicon: null
layout_spectrum: 0.09883
typography_spectrum: 1
title: Sun In Your Garden
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0079c2'
    - '#000000'
    - '#f5f5f5'
    - '#7f8000'
    - '#fb0003'
  brandStrength: 0.6875
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
