name: suninyourgarden
favicon: null
layout_spectrum: 0.50783
typography_spectrum: 0.63208
title: Sun In Your Garden
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#657686'
    - '#b0ab8d'
    - '#000600'
    - '#feed95'
    - '#cc7236'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
