name: suninyourgarden
favicon: null
layout_spectrum: 0.28608
typography_spectrum: 0.8005350939929485
title: Sun In Your Garden
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#657686'
    - '#b0ab8d'
    - '#000600'
    - '#feed95'
    - '#cc7236'
  brandStrength: 0.9580474914982915
  lightness: 0.6875
  saturation: 0.9156351047568023
  rhythmicContrast: 0.75
purpose: []
