name: suninyourgarden
favicon: null
layout_spectrum: 0.72505
typography_spectrum: 1
title: Sun In Your Garden
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#657686'
    - '#b0ab8d'
    - '#000600'
    - '#feed95'
    - '#cc7236'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
